name: action-update-timestamp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: run-update-timestamp
      run: ./update-timestamp.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
